Team.create!([
  {name: "Courious", batch: 1, stage: 2, end: nil, active: true, lead: "Justin Pfefferle", summary: "The Courious team wants to make delivery drivers' lives easier. We provide an all-in-one tool to simplify the job. With our software, you can quickly add orders, set routes, and track mileages.", notes: nil},
  {name: "ft_sprinklers", batch: 2, stage: 1, end: nil, active: true, lead: "Kenneth Cheung", summary: "Automated, smart sprinkler system for 42", notes: nil},
  {name: "Font of Data", batch: 1, stage: 2, end: nil, active: true, lead: "Mitchell Wooden", summary: "Font of Data is a faction-based territory control game where players will compete and cooperate to claim territory and gather resources. The game will be gathering data that the players generate for use in mathematical research on solving the Collatz Conjecture.", notes: nil},
  {name: "Bad Honey Bun Games", batch: 2, stage: 1, end: nil, active: true, lead: "Danny Seatern", summary: "Time crisis in VR", notes: nil},
  {name: "Marvin's Mirror", batch: 2, stage: 1, end: nil, active: true, lead: "Anastasia Zimina", summary: "Smart mirror designed for 42", notes: nil},
  {name: "Fitme", batch: 3, stage: 1, end: nil, active: true, lead: "Oleg Kovalenko", summary: "AR to help you try on clothes", notes: nil},
  {name: "Project Alea", batch: 3, stage: 1, end: nil, active: true, lead: "Erik Rintala", summary: "Using neural networks to build an optimizer for daily fantasy sports", notes: nil},
  {name: "Clive", batch: 3, stage: 1, end: nil, active: true, lead: "Phil Mclaughlin", summary: "Building an open source pathtracer", notes: nil},
  {name: "Kafali Pay", batch: 3, stage: 1, end: nil, active: true, lead: "Obsaa Abdalhalim", summary: "An app to send quick international transactions, starting with remittance payments", notes: nil},
  {name: "Wilderness Patrol", batch: 3, stage: 1, end: nil, active: true, lead: "Ian Wagner", summary: "An app to help the California State Park system", notes: nil}
])
User.create!([
  {intra: "iwagner", first: "Ian", last: "Wagner", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "etregoni", first: "Elliot", last: "Tregoni", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "mmorel", first: "Michael", last: "Morel", dorm: true, slackname: "", imac: "C02R46J4GG7J", notes: ""},
  {intra: "kcheung", first: "Kenneth", last: "Cheung", dorm: true, slackname: "", imac: "C02R46MHGG7J", notes: ""},
  {intra: "jpfeffer", first: "Justin", last: "Pfefferle", dorm: true, slackname: "", imac: "D25S20BWGG7V", notes: ""},
  {intra: "rlutt", first: "Robert", last: "Lutt", dorm: true, slackname: "", imac: "C02R44T7GG7J", notes: ""},
  {intra: "mwooden", first: "Mitchell", last: "Wooden", dorm: true, slackname: "", imac: "D25S20FXGG7V", notes: ""},
  {intra: "ddowty", first: "Daniel", last: "Dowty", dorm: true, slackname: "", imac: "D25S2083GG7V", notes: ""},
  {intra: "pmclaugh", first: "Phil", last: "McLaughlin", dorm: true, slackname: "", imac: "C02R32D7GG7J", notes: "Has AMD tower next to his desk."},
  {intra: "elopez", first: "Eric", last: "Lopez", dorm: false, slackname: "", imac: "", notes: ""},
  {intra: "lyoung", first: "Louis", last: "Young", dorm: false, slackname: "", imac: "", notes: ""},
  {intra: "azimina", first: "Anastasia", last: "Zimina", dorm: false, slackname: "", imac: "D25RX144GG7V", notes: ""},
  {intra: "adosiak", first: "Anastasia", last: "Dosiak", dorm: false, slackname: "", imac: "D25S20B7GG7V", notes: ""},
  {intra: "eupopa", first: "Eugeniu", last: "Popa", dorm: false, slackname: "", imac: "C02R52PFGG7J", notes: ""},
  {intra: "kmurray", first: "Kyle", last: "Murray", dorm: true, slackname: "", imac: "D25S20B5GG7V", notes: ""},
  {intra: "ksaetern", first: "Danny", last: "Saetern", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "sdarsie", first: "Sean", last: "Darsie", dorm: true, slackname: "", imac: "D25S20B0GG7V", notes: ""},
  {intra: "olkovale", first: "Oleg", last: "Kovalenko", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "mzaneri", first: "Michael", last: "Zaneri", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "aezzeddi", first: "Alex", last: "Ezzeddine", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "erintala", first: "Erik", last: "Rintala", dorm: true, slackname: "", imac: "D25S204ZGG7V", notes: ""},
  {intra: "jnederlo", first: "Jarvis", last: "Nederlof", dorm: false, slackname: "", imac: "D25S20BQGG7V", notes: ""},
  {intra: "scollet", first: "Sam", last: "Collet", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "oabdalha", first: "Obsaa", last: "Abdalhalim", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "bmontoya", first: "Brandon", last: "Montoya", dorm: true, slackname: "", imac: "", notes: ""},
  {intra: "aquint", first: "Lexi", last: "Quint", dorm: true, slackname: "", imac: "", notes: ""}
])
AllHand.create!([
  {team_id: 10, date: "2018-03-26", b_kpi: "Release on Play Store this Week", t_kpi: "Customer Changes from Jeremy", help: "None", blockers: "Photoshop not on Computers (42 has a license, but in use). ", other: "Met with Jeremy last week and talked about feature change and release. Might do a weekend trip soon. "},
  {team_id: 2, date: "2018-03-26", b_kpi: "Waiting on parts to arrive", t_kpi: "Install open sprinkler once it arrives", help: "", blockers: "", other: "Kenney to send resume to jennifer"},
  {team_id: 7, date: "2018-03-26", b_kpi: "Establish contact with ESPN guy.", t_kpi: "Measure against projections of other fantasy sites.", help: "Need to learn Julia in the near future.", blockers: "", other: ""},
  {team_id: 1, date: "2018-03-26", b_kpi: "140 Active Users", t_kpi: "Keep crashes at 1", help: "", blockers: "", other: "Flyers this week. One day in San Jose, one in Oakland."},
  {team_id: 5, date: "2018-03-26", b_kpi: "Setup ReadMe on Github", t_kpi: "Need more voice training. Need to figure out why pi is shutting itself off. ", help: "", blockers: "", other: "Deadline in 2 weeks (on Friday). Everyone NEEDS to train marvin.  Need women testers."},
  {team_id: 4, date: "2018-03-26", b_kpi: "Consumer website is live. Continue social media presence. Finalize and publish trailer.", t_kpi: "Finish Oculus Benchmark. Fix edge cases, try to reproduce bugs.", help: "", blockers: "Needs new HDMI cable.", other: "Story is \"what happens when ai takes over world\". Waiting on ticket to be resolved through oculus store."},
  {team_id: 9, date: "2018-03-26", b_kpi: "Reach out to potential customers.", t_kpi: "Finish styling, need to build backend.", help: "", blockers: "", other: ""},
  {team_id: 3, date: "2018-03-26", b_kpi: "Setup meeting with Jennifer.", t_kpi: "Action cables working in development but not production.", help: "", blockers: "", other: "How to wrap up project?"},
  {team_id: 8, date: "2018-03-26", b_kpi: "Setup blog, publish all 2 posts this week. Create another post. Shoot one minute video and publish this week.", t_kpi: "Looking into moving into realtime. Improving refraction. Start brainstorming ideas for objective testing. Generate portfolio of images.", help: "Need models, but models cost money.", blockers: "Get access to 3d printer (needs to be fixed for awhile). ", other: "Endorse team on linkedin."},
  {team_id: 6, date: "2018-03-26", b_kpi: "Spend less on GPUs. ", t_kpi: "Sneaker detector works well. Starting to figure out how to swap shoes.", help: "", blockers: "", other: "Less harsh pitch towards retailers. They are both partners and competitors. "}
])
BulkAttendance.create!([
  {title: "weekly meeting", date: "2018-03-26", attendees: ["", "jpfeffer", "rlutt", "iwagner", "etregoni", "mmorel", "kcheung", "mwooden", "ddowty", "pmclaugh", "elopez", "lyoung", "eupopa", "kmurray", "ksaetern", "sdarsie", "mzaneri", "aezzeddi", "erintala", "jnederlo", "scollet", "oabdalha", "bmontoya", "aquint"], desc: "azimina excused, kid is ill."}
])
Member.create!([
  {team_id: 1, intra: "jpfeffer", active: true},
  {team_id: 1, intra: "jcasino", active: false},
  {team_id: 1, intra: "rlutt", active: true},
  {team_id: 1, intra: "jaleman", active: false},
  {team_id: 10, intra: "iwagner", active: true},
  {team_id: 10, intra: "etregoni", active: true},
  {team_id: 10, intra: "aphan", active: false},
  {team_id: 2, intra: "mmorel", active: true},
  {team_id: 2, intra: "kcheung", active: true},
  {team_id: 3, intra: "palatorr", active: false},
  {team_id: 3, intra: "mwooden", active: true},
  {team_id: 3, intra: "ddowty", active: true},
  {team_id: 8, intra: "pmclaugh", active: true},
  {team_id: 8, intra: "elopez", active: true},
  {team_id: 8, intra: "lyoung", active: true},
  {team_id: 5, intra: "azimina", active: true},
  {team_id: 5, intra: "adosiak", active: true},
  {team_id: 5, intra: "eupopa", active: true},
  {team_id: 5, intra: "kmurray", active: true},
  {team_id: 4, intra: "ksaetern", active: true},
  {team_id: 4, intra: "sdarsie", active: true},
  {team_id: 6, intra: "olkovale", active: true},
  {team_id: 6, intra: "mzaneri", active: true},
  {team_id: 6, intra: "aezzeddi", active: true},
  {team_id: 7, intra: "erintala", active: true},
  {team_id: 7, intra: "jnederlo", active: true},
  {team_id: 7, intra: "scollet", active: true},
  {team_id: 9, intra: "oabdalha", active: true},
  {team_id: 9, intra: "bmontoya", active: true},
  {team_id: 9, intra: "aquint", active: true}
])